meta_product_name: "Groot"
meta_title: "Devenez les Gardiens de notre Galaxie !"
meta_description: "2 000 « GROOT » vont être plantés en cette Journée Internationale de la Terre, et nous vous donnons l’occasion de parrainer le vôtre. Participez à cette opération en plantant vous aussi un Groot, et devenez les Gardiens de notre Galaxie !"
meta_image: "image.jpg"                           # Une image dans votre dossier app/assets/images/
twitter_account: "@nomdevotrecompte"              # indispensable pour les Twitter Cards
